name: Build & Release
on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.1'

    - name: Build
      run: cd src && ./make.bash

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.head_ref || github.ref_name }}/${{ github.sha }}
        files: |
          bin/go
          bin/gofmt
