name: Build & Release
on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.3'

    - name: Build
      run: |
        export GOROOT_FINAL=$(go env GOROOT)
        export GOROOT_BOOTSTRAP=$(go env GOROOT)
        cd src
        ./make.bash -v

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.head_ref || github.ref_name }}/${{ github.sha }}
        files: |
          bin/go
